version: "3.9"

services:
  binarykeeda-ui:
    build:
      context: .
      args:
        VITE_PORT: ${VITE_PORT}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_MESSAGE_QUEUE_URL: ${VITE_MESSAGE_QUEUE_URL}
        VITE_CODE_EXECUTION_API: ${VITE_CODE_EXECUTION_API}
        VITE_PAYMENT_KEY: ${VITE_PAYMENT_KEY}
        VITE_PAYMENT_URL: ${VITE_PAYMENT_URL}
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
        VITE_LOGIN_URL: ${VITE_LOGIN_URL}
        VITE_ADMIN_URL: ${VITE_ADMIN_URL}
        VITE_FRONTEND_URL: ${VITE_FRONTEND_URL}

    ports:
      - "5173:80"

    restart: unless-stopped
