version: "3.8"

services:
  binarykeeda-ui-prod:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: binarykeeda-ui-prod
    args:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_MESSAGE_QUEUE_URL: ${VITE_MESSAGE_QUEUE_URL}
      VITE_CODE_EXECUTION_API: ${VITE_CODE_EXECUTION_API}
      VITE_PAYMENT_KEY: ${VITE_PAYMENT_KEY}
      VITE_PAYMENT_URL: ${VITE_PAYMENT_URL}
      VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
      VITE_LOGIN_URL: ${VITE_LOGIN_URL}
      VITE_ADMIN_URL: ${VITE_ADMIN_URL}
      VITE_FRONTEND_URL: ${VITE_FRONTEND_URL}
    restart: always
    ports:
      - "3030:80"
    env_file:
      - .env
    networks:
      - binarykeeda-network-prod
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  binarykeeda-network-prod:
    driver: bridge
